<?php

namespace PacientesBundle\Repository;

/**
 * analisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class analisisRepository extends \Doctrine\ORM\EntityRepository
{
}
